version: "3.9"
services:
  app:
    build:
      context: ../
      dockerfile: .buildkite/Dockerfile
    environment:
      DATABASE_URL: postgres://postgres:postgres@postgres:5432/decafsucks_test
    depends_on:
      postgres:
        condition: service_healthy
  postgres:
    image: postgres:15-alpine
    environment:
      POSTGRES_PASSWORD: postgres
    ports:
      - 5432
    healthcheck:
      test: pg_isready -U postgres -h 127.0.0.1
      interval: 5s
