steps:
  - label: Lint
    commands:
      - gem install standard
      - rubocop
    plugins:
      docker#v5.3.0:
        image: "ruby:3.2"
  - label: Run tests
    commands:
      - HANAMI_ENV=test bin/hanami db create
      - HANAMI_ENV=test bin/hanami db migrate
      - bundle exec rake tailwind:compile
      - bundle exec hanami assets compile
      - bundle exec rake
    plugins:
      - docker-compose#v3.10.0:
          config: .buildkite/docker-compose.yml
          run: app
