steps:
  - label: Run tests
    commands:
      - HANAMI_ENV=test bin/hanami db create
      - HANAMI_ENV=test bin/hanami db migrate
      - bundle exec rake
    plugins:
      - docker-compose#v3.10.0:
          config: .buildkite/docker-compose.yml
          run: app
