name: ci

on: [push]

jobs:
  rubocop:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.4.4
          bundler-cache: true
      - name: Rubocop
        run: bundle exec rubocop
  tests:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:17-alpine
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: password
        ports:
          - 5432:5432
    steps:
      - uses: actions/checkout@v4
      - uses: ruby/setup-ruby@v1
        name: Set up Ruby
        with:
          ruby-version: 3.4.4
          bundler-cache: true
      - uses: actions/setup-node@v4
        name: Set up Node
        with:
          node-version: 22
          cache: npm
      - run: npm ci
      - name: Run tests
        env:
          DATABASE_URL: postgres://postgres:password@localhost:5432/decafsucks_test
        run: |
          HANAMI_ENV=test bundle exec hanami db create
          HANAMI_ENV=test bundle exec hanami db migrate --no-dump
          bundle exec rake tailwind:compile
          bundle exec hanami assets compile
          bundle exec rake
